version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    # image: ift6758/serving:latest
    ports:
      - "5000:5000"
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
###### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    ports:
      - 8501:8501