FROM python:3.9-slim

WORKDIR /code

ADD ./serving/app.py /code
ADD ./requirements-prod.txt /code

RUN pip install --no-cache-dir -r requirements-prod.txt

ENV COMET_API_KEY=""

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]